---
custom_projects:
  - name: jfr-merger
    repo: https://github.com/izual0110/jfr-merger.git
    version: main

  - name: RootCauseLab
    repo: https://github.com/izual0110/RootCauseLab.git
    version: main
