---
- name: Ensure tools directory exists
  file:
    path: "{{ ansible_env.HOME }}/tools"
    state: directory
    mode: "0755"

- name: Clone my projects
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/tools/{{ item.name }}"
    version: main
    update: true
  loop:
    - name: jfr-merger
      repo: https://github.com/izual0110/jfr-merger.git
    - name: RootCauseLab
      repo: https://github.com/izual0110/RootCauseLab.git
