---
third_party_tools_dir: "{{ ansible_env.HOME }}/tools"
third_party_downloads_dir: "{{ third_party_tools_dir }}/.downloads"

third_party_tools:
  - name: jol
    version: "0.17"
    archive_url: "https://github.com/openjdk/jol/archive/refs/tags/0.17.tar.gz"
    archive_name: "jol-0.17.tar.gz"
    extract_to: "{{ third_party_tools_dir }}"

  - name: async-profiler
    version: "4.3"
    archive_url: "https://github.com/async-profiler/async-profiler/releases/download/v4.3/async-profiler-4.3-linux-x64.tar.gz"
    archive_name: "async-profiler-4.3-linux-x64.tar.gz"
    extract_to: "{{ third_party_tools_dir }}"

  - name: eclipse-mat
    version: "1.16.1"
    archive_url: "https://mirror.kakao.com/eclipse/mat/1.16.1/rcp/MemoryAnalyzer-1.16.1.20250109-linux.gtk.x86_64.zip"
    archive_name: "MemoryAnalyzer-1.16.1-linux.gtk.x86_64.zip"
    extract_to: "{{ third_party_tools_dir }}/eclipse-mat-1.16.1"

  - name: jmc
    version: "9.1.1"
    archive_url: "https://cdn.azul.com/zmc/bin/zmc9.1.1.1.41-ca-linux_x64.tar.gz"
    archive_name: "zmc9.1.1.1.41-ca-linux_x64.tar.gz"
    extract_to: "{{ third_party_tools_dir }}"

  - name: visualvm
    version: "2.2.1"
    archive_url: "https://github.com/oracle/visualvm/releases/download/2.2.1/visualvm_221.zip"
    archive_name: "visualvm_221.zip"
    extract_to: "{{ third_party_tools_dir }}"
