---
- name: Ensure tools directory exists
  file:
    path: "{{ third_party_tools_dir }}"
    state: directory
    mode: "0755"

- name: Ensure tools tmp directory exists
  file:
    path: "{{ third_party_downloads_dir }}"
    state: directory
    mode: "0755"

- name: Ensure extraction directories exist
  file:
    path: "{{ item.extract_to }}"
    state: directory
    mode: "0755"
  loop: "{{ third_party_tools }}"

- name: Download third-party archives
  get_url:
    url: "{{ item.archive_url }}"
    dest: "{{ third_party_downloads_dir }}/{{ item.archive_name }}"
    mode: "0644"
  loop: "{{ third_party_tools }}"

- name: Unpack third-party archives
  unarchive:
    src: "{{ third_party_downloads_dir }}/{{ item.archive_name }}"
    dest: "{{ item.extract_to }}"
    remote_src: true
    creates: "{{ item.extract_to }}/.installed-{{ item.name }}-{{ item.version }}"
  loop: "{{ third_party_tools }}"

- name: Create install marker files
  file:
    path: "{{ item.extract_to }}/.installed-{{ item.name }}-{{ item.version }}"
    state: touch
    mode: "0644"
  loop: "{{ third_party_tools }}"
